name: RSKB

project:
  version:
  download_url:
  download_text:

license:
  software:
  software_url:
  docs:
  docs_url:

links:
  header:
    - title:
      icon:
      brand:
      url:
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/royfrancis/rskb
  footer:
    - title: Github
      icon: github
      brand: true
      url: https://github.com/royfrancis/rskb
    - title: Issues
      icon: bug
      url: https://github.com/royfrancis/rskb/issues

  logo:
    src: /assets/logo.svg 
    href: https://nbis.se/
    alt: nbis-logo
  
ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#9fbc53"
    light: "#95b540"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#86a239"
      color2: "#687e2c"
    light:
      color1: "#96b43f"
      color2: "#85a038"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
  toc:
    highlight:
      light:
      dark:

social:
  github:
    enabled: false
  twitter:
    enabled: false
  facebook:
    enabled: false

markdown: kramdown
remote_theme: royfrancis/jekyll-theme-trianglify@lime
